# get duplicate

super_lst = ['character_global_ctrlShape', 'sknJnt_spine1_root_ctrlShape', 'sknJnt_spine2_ctrlShape', 'sknJnt_spine3_ctrlShape', 'sknJnt_neck1_ctrlShape', 'sknJnt_neck2_ctrlShape', 'sknJnt_neck3_ctrlShape', 'sknJnt_jaw_ctrlShape', 'sknJnt_tongue1_ctrlShape', 'sknJnt_tongue2_ctrlShape', 'sknJnt_tongue3_End_ctrlShape', 'l_ikHip_ctrlShape', 'fkJnt_l_leg1_ctrlShape', 'fkJnt_l_leg2_ctrlShape', 'fkJnt_l_leg3_ctrlShape', 'fkJnt_l_foot1_ctrlShape', 'fkJnt_l_foot2_ctrlShape', 'r_ikHip_ctrlShape', 'fkJnt_r_leg1_ctrlShape', 'fkJnt_r_leg2_ctrlShape', 'fkJnt_r_leg3_ctrlShape', 'fkJnt_r_foot1_ctrlShape', 'fkJnt_r_foot2_ctrlShape', 'fourArrow_ctrlShape', 'fourArrow_ctrlShape1', 'fourArrow_ctrlShape2', 'fourArrow_ctrlShape3', 'fourArrow_ctrlShape4', 'fourArrow_ctrlShape', 'fourArrow_ctrlShape5', 'fourArrow_ctrlShape6', 'fourArrow_ctrlShape7', 'fourArrow_ctrlShape8', 'fourArrow_ctrlShape', 'fourArrow_ctrlShape9', 'fourArrow_ctrlShape10', 'fourArrow_ctrlShape11', 'fourArrow_ctrlShape12', 'arrowTwist_ctrlShape', 'arrowTwist_ctrlShape1', 'l_ikFoot_ctrlShape', 'l_ftCtrl_inner_footShape', 'l_ftCtrl_inner_footAShape', 'l_ftCtrl_inner_footBShape', 'l_ftCtrl_outer_footShape', 'l_ftCtrl_outer_footAShape', 'l_ftCtrl_outer_footBShape', 'l_ftCtrl_heelShape', 'l_ftCtrl_heelAShape', 'l_ftCtrl_heelBShape', 'l_ftCtrl_toe_endShape', 'l_ftCtrl_toe_endAShape', 'l_ftCtrl_toe_endBShape', 'l_ftCtrl_toeShape', 'l_ftCtrl_toeAShape', 'l_ftCtrl_toeBShape', 'l_ftCtrl_ankleShape', 'l_ftCtrl_ankleAShape', 'l_ftCtrl_ankleBShape', 'l_ftCtrl_toe_wiggleShape', 'l_knee_poleVector_ctrlShape', 'l_ankle_poleVector_ctrlShape', 'r_ikFoot_ctrlShape', 'r_ftCtrl_inner_footShape', 'r_ftCtrl_inner_footAShape', 'r_ftCtrl_inner_footBShape', 'r_ftCtrl_outer_footShape', 'r_ftCtrl_outer_footAShape', 'r_ftCtrl_outer_footBShape', 'r_ftCtrl_heelShape', 'r_ftCtrl_heelAShape', 'r_ftCtrl_heelBShape', 'r_ftCtrl_toe_endShape', 'r_ftCtrl_toe_endAShape', 'r_ftCtrl_toe_endBShape', 'r_ftCtrl_toeShape', 'r_ftCtrl_toeAShape', 'r_ftCtrl_toeBShape', 'r_ftCtrl_ankleShape', 'r_ftCtrl_ankleAShape', 'r_ftCtrl_ankleBShape', 'r_ftCtrl_toe_wiggleShape', 'r_knee_poleVector_ctrlShape', 'r_ankle_poleVector_ctrlShape', 'l_ikAnkleOff_ctrlShape', 'l_legSwtch_ctrlShape', 'l_legSwtch_ctrlAShape', 'l_legSwtch_ctrlBShape', 'r_ikAnkleOff_ctrlShape', 'r_legSwtch_ctrlShape', 'r_legSwtch_ctrlAShape', 'r_legSwtch_ctrlBShape', 'tail1_fkCtrlShape', 'tail2_fkCtrlShape', 'tail3_fkCtrlShape', 'tail4_fkCtrlShape', 'tail5_fkCtrlShape', 'tail6_fkCtrlShape', 'tail7_fkCtrlShape', 'tail_swch_ctrlShape', 'tail_swch_ctrlAShape', 'tail_swch_ctrlBShape', 'tail_ikHndl_curveShape', 'tail_ikHndl_curveShapeOrig']

seen = set()
dupes = []
for x in super_lst:
    if x in seen:
        dupes.append(x)
    else:
        seen.add(x)

print(dupes)
