from . import character_rig
from . import character_rig_quadruped
from . import fk_spine_rig
from . import extra_rig
from . import leg_rig
from . import face_rig
from . import clavicle_rig
from . import arm_rig
from . import quadruped_leg_rig
from . import tail_tentacle_rig
from . import arm_wing_rig
